### ISSUE TITLE
Overlay broken

### ISSUE THREAD

**Issue by techieAgnostic** [WillPower3309/swayfx#281] opened 2024-04-10 09:56 UTC
The overlay exposed at `overlays.default` from commit `8afe66a` is overriding `pkgs.swayfx-unwrapped` instead of (I believe it should be) `pkgs.sway-unwrapped`, causing configurations using that overlay to fail with the following error:

```
error:
       … while calling the 'head' builtin

         at /nix/store/9xacbyc7dywnxssdz5xc2nyi7pj0hw3k-source/lib/attrsets.nix:922:11:

          921|         || pred here (elemAt values 1) (head values) then
          922|           head values
             |           ^
          923|         else

       … while evaluating the attribute 'value'

         at /nix/store/9xacbyc7dywnxssdz5xc2nyi7pj0hw3k-source/lib/modules.nix:807:9:

          806|     in warnDeprecation opt //
          807|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          808|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'swayfx-unwrapped' missing

       at /nix/store/qpfl8gc9n4sky30lcmv8f1q4iczp81ph-source/flake.nix:14:12:

           13|         swayfx-unwrapped =
           14|           (pkgs.swayfx-unwrapped.override {
             |            ^
           15|             # When the sway 1.9 rebase is finished, this will need to be overridden.
       Did you mean sway-unwrapped?
```

**Comment by WillPower3309** [comment] 2024-04-10 15:56
Mind tying again? https://github.com/WillPower3309/swayfx/commit/167a4ea0aec93d51e4c606ffdbe3a195d12da6e3 may have fixed this

**Comment by Sntx626** [comment] 2024-04-10 17:19
> Mind tying again? [167a4ea](https://github.com/WillPower3309/swayfx/commit/167a4ea0aec93d51e4c606ffdbe3a195d12da6e3) may have fixed this

I don't think that the commit has something to do with it. The commit only changes the `formatter` output of the flake, not the overlay.

---

Instead I think the problem is a result of the following.

The sway**fx** flake overwrites sway**fx**-unwrapped with it's default overlay.

However since sway**fx**-unwrapped package is only available in nixpkgs-unstable, it should throw the mentioned error if the overlay is applied to nixpkgs-stable (for now).

---

We could add another `overlays.sway-unwrapped` or `overlays.legacy` that overrides the sway-unwrapped package for now.

---

I might be completely off though, since I haven't used overlays that much.

**Comment by ozwaldorf** [comment] 2024-04-10 20:58
To use it on stable nixpkgs, you should be able to just use the `insert` overlay, which will use the pinned nixpkgs in the flake instead of overriding your local nixpkgs directly. We could override sway direcly like before, but we'd need to make sure this mirrors all the minor overrides the unstable swayfx nixpkg does for us (ie, wlroots = wlroots_0_16)

**Comment by WillPower3309** [comment] 2024-04-15 05:41
@ozwaldorf can we close this now?

**Closed** 2024-04-20 02:35 UTC
Labels: bug
