### ISSUE TITLE
Enable background blur for Waybar Tooltips

### ISSUE THREAD

**Issue by aspauldingcode** [WillPower3309/swayfx#330] opened 2024-07-17 18:26 UTC
# Enable background blur for Waybar
layer_effects "waybar" blur enable; corner_radius 10

doesn't enable blur for tooltips.

**Comment by ozwaldorf** [comment] 2024-07-18 12:52
Duplicate of #260 ?

**Comment by ErikReider** [comment] 2024-07-18 13:30
Duplicate

**Closed** 2024-07-18 13:30 UTC
Labels: enhancement
