### ISSUE TITLE
Effects improperly rendered on rotated output

### ISSUE THREAD

**Issue by qubidt** [WillPower3309/swayfx#130] opened 2023-03-20 08:33 UTC
### Please fill out the following:
- **Swayfx Version:**
  - `sway -v`: `sway version 0.2`
  - [AUR package](https://aur.archlinux.org/packages/swayfx) `0.2-2`

- **Debug Log:** https://gist.github.com/qubidt/f700af4d743b404c6fd1b94a6de3354d#file-sway-log

- **Configuration File:** https://gist.github.com/qubidt/f700af4d743b404c6fd1b94a6de3354d#file-sway-conf

- **Description:**
With an output rotated 90deg clockwise (`transform 270`), the transform applied to the output seem not have been applied properly to the effects (rounded corners and shadows). Screen recording:

https://user-images.githubusercontent.com/6306455/226285638-267054ed-f061-4486-ba97-6f8493a3c74a.mp4

**Comment by ErikReider** [comment] 2023-03-20 08:41
Duplicate of #47

**Closed** 2023-03-20 08:42 UTC
Labels: bug

**Comment by qubidt** [comment] 2023-03-20 10:28
didn't see that, apologies
