### ISSUE TITLE
Bottom corners of submenues are rounded when using titlebars

### ISSUE THREAD

**Issue by RicArch97** [WillPower3309/swayfx#95] opened 2023-01-16 18:34 UTC
Relevant configuration options:
```
corner_radius 10
default_border normal 1
```

Screenshot:
![2023-01-16T19:01:12,053472725+01:00](https://user-images.githubusercontent.com/61013287/212745946-08c2fc47-6979-4351-b100-b88a0c2f768f.png)

This happens in Google Chome. Not all apps are affected.

**Comment by ErikReider** [comment] 2023-01-16 18:41
Hmm. Can't reproduce... Are you running it with XWayland?

**Comment by RicArch97** [comment] 2023-01-16 18:57
My instance is launched with ` --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations` which is automatically done on NixOS after setting the `NIXOS_OZONE_WL` environment variable. It uses the Wayland backend, as it has an app-id.

**Comment by ErikReider** [comment] 2023-01-16 20:52
https://github.com/WillPower3309/swayfx/blob/1baba77c74302b8c1f212e851f194deae0fae46b/sway/desktop/render.c#L1411-L1423

Seems to be the issue

**Comment by WillPower3309** [comment] 2023-01-18 07:00
We actually only round the bottom two surfaces of the window when rendering a surface with a titlebar. The titlebar's corners are rounded, but for the window surface itself, only the bottom corners are rounded. That said, for view popups we should'nt have that has_titlebar. In fact, we should probably set the corner_radius to 0 as well.

**Comment by WillPower3309** [comment] 2023-01-18 07:01
This is an easy fix, I'lldo it tomorrow

**Comment by WillPower3309** [comment] 2023-01-23 07:36
Should be fixed by https://github.com/WillPower3309/swayfx/commit/dd67fdb6c3824eae4c2f0207526e155e0d390d17

**Closed** 2023-01-23 07:36 UTC
Labels: bug
